### ISSUE TITLE
Figure out how to support representations of Eccelerate groups / adjust tests to cope with lack of support

### ISSUE THREAD

**Issue by rheitjoh** [cryptimeleon/eccelwrap#1]
The eccelerate groups cannot offer representation functionality as the eccelerate API does not allows us to instantiate `EllipticCurve` and `ExtensionField` objects directly.
Therefore `getRepresentation()` methods cannot be implemented for the group classes.

I have those methods throwing a `UnsupportedOperationException` but it leads to the tests failing.
Since we won't be able to properly implement the representation stuff, we should at least adjust the tests to not fail.

**Comment by feidens** [comment]
Maybe we can contact the Eccelerate developers to change the access to the classes. Any thoughts on this?

**Comment by rheitjoh** [comment]
I think it actually might be still possible to implement the representation stuff.

The pairing factory supposedly instantiates predefined `Pairing` objects for certain base field sizes. So we could just represent those parameters we use to instantiate the `Pairing` object. Then, when deserializing, we reinstantiate the `Pairing` object and get whatever group we wanted to deserialize from that. This rides on the `Pairing` object instantiation being deterministic, which it should be for the parameters we offer.

Having access to the constructor and the necessary parameters to serialize/deserialize would of course be preferable, but I am unsure whether they would do such large changes to the API just because of us.

**Comment by rheitjoh** [comment]
Seems like there is a bug in the `equals()` implementation of the `Pairing` class. If you look at it through a debugger, the `pairing.g.l` fields return `false`, even though the fields of `pairing.f.l` are equal. So if I instantiate the `Pairing` object again via the factory, the new pairing wont equal the old one, even though they are functionally the same.

**Comment by rheitjoh** [comment]
Ok, I will be implementing representation support by just serializing the pairing factory parameters (pairing type and group bit size) and then recreating the necessary objects from that.
